language: python
python:
  - "2.7"
  - "3.3"
install:
  - sudo apt-get update -qq
  - sudo apt-get install liblua5.1-0-dev liblua50-dev liblualib50-dev
  - pip install --quiet --upgrade pip
  - pip install --quiet -r test-requirements.txt
  - pip install .
script:
  - py.test databuild
